version: '3.1'

services:
  server:
    image: golang:1.22.4
    hostname: web
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    command: './cmd/server/gophkeeper -s /app/swagger-ui/'
    env_file:
      - .env
    ports:
      - $PORT:$PORT
      - $PORT_REST:$PORT_REST
    depends_on:
      - db

  db:
    image: postgres
    hostname: db
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    hostname: pgadmin4
    restart: always
    env_file:
      - .env
    ports:
      - 80:80
